# Headless service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  clusterIP: {{ .Values.service.clusterIP }}
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
